USE [master]
GO

/****** Object:  Database [inDoorAirQuality]    Script Date: 22/10/2014 11:23:39 ******/
CREATE DATABASE [inDoorAirQuality] ON  PRIMARY 
( NAME = N'inDoorAirQuality', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\inDoorAirQuality.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'inDoorAirQuality_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\inDoorAirQuality_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [inDoorAirQuality] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [inDoorAirQuality].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [inDoorAirQuality] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET ARITHABORT OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [inDoorAirQuality] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [inDoorAirQuality] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET  DISABLE_BROKER 
GO

ALTER DATABASE [inDoorAirQuality] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [inDoorAirQuality] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [inDoorAirQuality] SET  MULTI_USER 
GO

ALTER DATABASE [inDoorAirQuality] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [inDoorAirQuality] SET DB_CHAINING OFF 
GO

ALTER DATABASE [inDoorAirQuality] SET  READ_WRITE 
GO


